name: Deploy NestJS App with Docker to EC2
on:
  push:
    branches:
      - main # Trigger deployment on pushing to main branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t surendrawagle/nodejs-app -f Dockerfile .
      - name: Publish Image to docker hub
        run: docker push surendrawagle/nodejs-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull surendrawagle/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name nodejs-app-container -e DATABASE_URL=${{ secrets.DATABASE_URL }} surendrawagle/nodejs-app
      - name: Run Docker Container
        run: docker run -d -p 5000:5000 --name nodejs-app-container \
          -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
          -e MAIL_HOST=${{ secrets.MAIL_HOST }} \
          -e MAIL_USER=${{ secrets.MAIL_USER }} \
          -e MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
          -e MAIL_FROM=${{ secrets.MAIL_FROM }} \
          -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
          -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
          -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
          surendrawagle/nodejs-app:latest

# name: Deploy Node Application

# on:
#   push:
#     branches:
#       - mern-ec2-docker

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v4
#       - name: Login to docker hub
#         run: docker login -u 
#       - name: Build Docker Image
#         run: docker build -t integrationninjas/nodejs-app  .
#       - name: Publish Image to docker hub
#         run: docker push integrationninjas/nodejs-app:latest

#   deploy:
#     needs: build
#     runs-on: self-hosted
#     steps:
#       - name: Pull image from docker hub
#         run: docker pull integrationninjas/nodejs-app:latest
#       - name: Delete old container
#         run: docker rm -f nodejs-app-container
#       - name: Run Docker Container
#         run: docker run -d -p 4000:4000 --name nodejs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' integrationninjas/nodejs-app
